.SUFFIXES : .o .cpp .c

OBJS =\
 julday.o\
 caldat.o\
 utl_hypd.o\
 utl_time.o\
 hypo71_core.o\
 hypo71.o

LIB = libhypo71.a
INCLUDES     = -I../include
DEFINES      =
CCFLAGS      = -ggdb -Wall
#CCFLAGS      = -O2
LDFLAGS      =
CXXFLAGS     = $(CCFLAGS) $(DEFINES) $(INCLUDES)
CFLAGS       = $(CCFLAGS) $(DEFINES) $(INCLUDES)

AR = ar -rs
CCPLUS = g++
CC     = gcc

.cpp.o: ; $(CCPLUS) -c $(CXXFLAGS) $*.cpp
.c.o: ; $(CC) -c $(CFLAGS) $*.c

all: $(LIB)

$(LIB): $(OBJS) 
	$(RM) $@
	$(AR) $@ $(OBJS)
	cp $(LIB) ../lib/$(LIB)

clean:
	$(RM) *.o *~ $(LIB) Makefile.bak Makefile.BAK

depend:
	makedepend $(INCLUDES) *.cpp

# DO NOT DELETE

