#! /bin/bash

nohup python live_data_adquisition.py &

nohup python do_autopick.py &
nohup python do_autoloc.py &
nohup python do_rsam_and_ssam.py &

nohup python export_helicorder.py &
nohup python export_waveforms.py &
nohup python export_triggers.py &
nohup python export_seismicity_rate.py &

nohup python export_kml.py &
nohup python web/PyGema_Web/manage.py runserver 0.0.0.0:9000 &
#nohup python sync.py & 

ps aux | grep python


